In [1]:
a=['sting',22,333,44,55,66,77,88,99]
a

[11, 22, 333, 44, 55, 66, 77, 88, 99]

In [67]:
#count how many times the number is in the list
a.count(66)

0

In [73]:
a.replace("sting","replaced")
a

AttributeError: 'list' object has no attribute 'replace'

In [2]:
a[2]

333

In [3]:
a[0]

11

In [4]:
a[-1]

99

In [5]:
len(a)

9

In [10]:
a.append('string')

In [7]:
a

[11, 22, 333, 44, 55, 66, 77, 88, 99, 'string']

In [9]:
a

[11, 22, 333, 44, 55, 66, 77, 88, 99, 'string', 'string']

In [11]:
a.insert(0,"zeroIndex")

In [12]:
a

['zeroIndex',
 11,
 22,
 333,
 44,
 55,
 66,
 77,
 88,
 99,
 'string',
 'string',
 'string']

In [13]:
a.remove(0)

ValueError: list.remove(x): x not in list

In [14]:
a.remove('string')

In [15]:
a

['zeroIndex', 11, 22, 333, 44, 55, 66, 77, 88, 99, 'string', 'string']

In [16]:
a.index('string')

10

In [17]:
a.index('zeroIndex')

0

In [18]:
a.len()

AttributeError: 'list' object has no attribute 'len'

In [19]:
len(a)

12

In [20]:
type(a)

list

In [22]:
type(a[0])

str

In [23]:
type(a[12])

IndexError: list index out of range

In [24]:
type(a[11])

str

In [25]:
type(a[101])

IndexError: list index out of range

In [26]:
type(a[10])

str

In [27]:
type(a[9])

int

In [30]:
a=[3,6,9,12,15,18]
a[0:3]

[3, 6, 9]

In [31]:
a[:4]

[3, 6, 9, 12]

In [32]:
a[-1:-3]

[]

In [33]:
a[-3:-1]

[12, 15]

In [34]:
var=[3,6,9,12,15,18]
var[1::2]

[6, 12, 18]

In [35]:
lst=[1,2,[11,22,33]]
len(lst)

3

In [36]:
b[-1]

NameError: name 'b' is not defined

In [37]:
lst[-1]

[11, 22, 33]

In [38]:
lst[-1][0]

11

In [39]:
a=[11,22,33]+[22,55,66]
a

[11, 22, 33, 22, 55, 66]

In [40]:
a.replace(11,10)

AttributeError: 'list' object has no attribute 'replace'

In [41]:
a.replace(0,11)

AttributeError: 'list' object has no attribute 'replace'

In [42]:
a.remove(66)

In [43]:
del[0]

SyntaxError: can't delete literal (<ipython-input-43-fa755b85c842>, line 1)

In [44]:
a.del[0]

SyntaxError: invalid syntax (<ipython-input-44-a5a3bf930fb7>, line 1)

In [45]:
del(a[0])

In [46]:
pop(a[0])

NameError: name 'pop' is not defined

In [47]:
a.pop(55)

IndexError: pop index out of range

In [48]:
a.pop([0])

TypeError: 'list' object cannot be interpreted as an integer

In [57]:
a=[range(1,101)]
a

[range(1, 101)]

In [50]:
a

[range(1, 101, 2)]

In [52]:
a=list(range(0,101))

In [54]:
max(a)

100

In [55]:
min(a)

0

In [58]:
import numpy as np

In [75]:
arr=np.array([[11,22,33],[44,55,66]])
arr
arr.shape

(2, 3)

In [64]:
one_dim=np.array([2,4,5])
one_dim

array([2, 4, 5])

In [74]:
one_dim.size

3

In [77]:
b=np.array([100,101,102,103])
b+10

array([110, 111, 112, 113])

In [78]:
b[0]

100

In [81]:
g=np.array([[1,2,3],[4,5,6]])
#I want to get 5 means 2nd row 2nd column


IndexError: index 2 is out of bounds for axis 0 with size 2

In [84]:
#There is no second row because it start with index 0
g[1,2]

6

In [83]:
#to get the first row
g[0]

array([1, 2, 3])

In [85]:
type(g)

numpy.ndarray

In [86]:
type(g[0])

numpy.ndarray

In [87]:
#to convert array into list
list(g)

[array([1, 2, 3]), array([4, 5, 6])]

In [92]:
n=list([range(0,100)])
n=np.array(n)

In [93]:
type(n)

numpy.ndarray

In [94]:
n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [97]:
l1=np.array([10,20,30,40,50,60,70,80,90])
l2=np.array([5,10,15,20,30,35,40,45,50])
l2-2*l1

array([ -15,  -30,  -45,  -60,  -70,  -85, -100, -115, -130])

In [ ]:
#We can apply mathermatical operations on the array

In [96]:
l1/l2

array([2.        , 2.        , 2.        , 2.        , 1.66666667,
       1.71428571, 1.75      , 1.77777778, 1.8       ])

In [98]:
#array is not a heterogenous, it takes only homogenous elements
np.array([2,4,5,'string'])

array(['2', '4', '5', 'string'], dtype='<U11')

In [5]:
import numpy as np
np.random.rand(10)

array([0.82017184, 0.71938489, 0.66039442, 0.42692141, 0.3141018 ,
       0.59124982, 0.47078017, 0.67330852, 0.8136613 , 0.60309848])

In [9]:
np.random.rand(10)

array([0.90249082, 0.81982577, 0.17107109, 0.70394531, 0.16351375,
       0.3022649 , 0.8938315 , 0.48138985, 0.01090785, 0.68812082])

In [11]:
#It gives us an integer between 0 and 9
np.random.randint(10)

5

In [16]:
#Here we give a range means we want an iteger between 5 and 7
np.random.randint(5,7)

6

In [18]:
#Here it gives 3 integers between 0 and 5
np.random.randint(0,6,3)

array([4, 3, 5])

In [3]:
import numpy as np

In [28]:
price=np.random.randint(100,150,15)

In [37]:
#The numbers greater than 125 and less than 150
~price[price>125]

array([-141, -145, -144, -146, -143, -131, -143, -147, -142, -138],
      dtype=int32)

In [38]:
#Here we find the length of those numbers greater than 125
len(price[price>125])

10

In [ ]:
np.