In [3]:
a=int(input("Enter any number: "))
if(a%2==0):
    print("The number is Even.")
else:
    print("The number is odd.")

Enter any number: 5
The number is odd.


In [4]:
import numpy as np

In [5]:
a=np.array([2,1,5,6,6])
sum(a)

20

In [16]:
a=2

In [17]:
b=str(a)

In [18]:
b

'2'

In [19]:
float(a)

2.0

In [29]:
a=np.array([range(0,5000,500)])

In [30]:
a

array([[   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]])

In [40]:
b=a>=2000
b

array([[False, False, False, False,  True,  True,  True,  True,  True,
         True]])

In [44]:
c=b<=4000
c

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [43]:
a[c]

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500])

In [83]:
a=list(range(0,5500,500))
a


[0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000]

In [84]:
a[4:9]   

[2000, 2500, 3000, 3500, 4000]

In [85]:
b
for i in a:
    if i<=2000 and i>=4000:
        b.append(i)
b

[2000, 2500, 3000, 3500, 4000]

In [86]:
var=np.random.randint(10,20,5)
var

array([18, 17, 14, 16, 18])

In [87]:
new_var=var[var>15]
new_var

array([18, 17, 16, 18])

In [148]:
temp=list(range(0,5500,500))
temp

[0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000]

In [149]:
a=np.array(temp)
a

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000])

In [150]:
temp=(a>=2000)
temp

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [151]:
a=a[temp]

In [152]:
a

array([2000, 2500, 3000, 3500, 4000, 4500, 5000])

In [153]:
temp=a<=4000
temp

array([ True,  True,  True,  True,  True, False, False])

In [154]:
a=a[temp]
a

array([2000, 2500, 3000, 3500, 4000])

In [159]:
import numpy as np
two_dimentional=np.array([[2,1,3],[8,9,6]])
print(two_dimentional)
two_dimentional.shape

[[2 1 3]
 [8 9 6]]


(2, 3)

In [162]:
#randn ----> It will also give negative numbers
np.random.randn(4)

array([-1.05319494,  0.41510698,  0.08203192,  0.70219731])

In [165]:
#It will give you numbers between 0 and 1 ----  and 4 rows and 2 columns
v=np.random.rand(4,2)

In [166]:
v
v.shape

(4, 2)

In [169]:
#This will round the numbers to 2 digits after point(.)
v.round(2)
#np.round(v,3)

array([[0.6  , 0.204],
       [0.046, 0.846],
       [0.412, 0.153],
       [0.989, 0.653]])

In [171]:
np.round(6.48,1)

6.5

In [172]:
#Ceiling---- matlab chat

np.ceil(4.2)

5.0

In [173]:
#floor

np.floor(5.9)

5.0

In [178]:
np.round(1.5)

2.0

In [188]:
#First approach for matrix through randint

a=np.random.randint(600,610,(2,3))
a

array([[609, 606, 602],
       [605, 608, 609]])

In [189]:
#Second approach for matrix through randint method.
b=np.random.randint(600,610,size=(2,3))
b

array([[609, 607, 600],
       [604, 609, 600]])

In [190]:
b[0,0]

609

In [192]:
b[-1,-1]

600

In [193]:
#sorting ---> It is by default in assending order

In [200]:
arr=np.random.randint(1,11,4)

In [201]:
arr

array([6, 2, 2, 6])

In [202]:
arr.sort

<function ndarray.sort>

In [204]:
np.sort(arr)

array([2, 2, 6, 6])

In [205]:
#Sorting for matix or multidimentional array

In [206]:
a=np.random.randint(0,10,(4,5))
a

array([[8, 4, 8, 5, 0],
       [2, 6, 3, 5, 0],
       [9, 0, 5, 6, 2],
       [0, 0, 3, 0, 3]])

In [214]:
#For Column sum
a.sum(0)

array([19, 10, 19, 16,  5])

In [208]:
#For Row sum
a.sum(1)

array([25, 16, 22,  6])

In [209]:
#Or
a.sum(axis=0)

array([19, 10, 19, 16,  5])

In [210]:
#Or
a.sum(axis=1)

array([25, 16, 22,  6])

In [211]:
#sorted
sorted(arr) ''aLi''

[2, 2, 6, 6]

In [216]:
a=np.array(['Ali','aLi','aLi','ALi','umair','kamran','nahin','waqar','uzair','shafi','umar'])
a

array(['Ali', 'aLi', 'aLi', 'ALi', 'umair', 'kamran', 'nahin', 'waqar',
       'uzair', 'shafi', 'umar'], dtype='<U6')