In [1]:
var1=[22,77.44,"String"]
var1


[22, 77.44, 'String']

In [2]:
var2=[2,"apple",99.9]
var2

[2, 'apple', 99.9]

In [3]:
var3=[True,False,True,False]
var3

[True, False, True, False]

In [5]:
var=[11,22,33,44.4,'string']
#Slicing
var[0]
var[1]

22

In [6]:
var[4]

'string'

In [8]:
#here we give a range means we want from this place to this placerav
var[0:4]

#here the zero is inclsive while the four is exclusive
#The index in python starts from zero

[11, 22, 33, 44.4]

In [12]:
#here we do reverse slicing 
var[-4:-1]
#The output should be 22 and 33 and 44.4 because it will start from left to right in this case.


[22, 33, 44.4]

In [13]:
#Dicing... It means that we extract variable with a gap means we want first element then forth and then sixth ...
var[::2] #start from zero till last with 2 gaps after first

[11, 33, 'string']

In [14]:
var

[11, 22, 33, 44.4, 'string']

In [16]:
a=[11,12,130]


In [17]:
var = [11, 22, 33, 44, 55]

In [18]:
var[-4:]

[22, 33, 44, 55]

In [19]:
var[1:2]

[22]

In [25]:
lsit_of_list=[10,20,30,[5,10,15,20]]
lsit_of_list

[10, 20, 30, [5, 10, 15, 20]]

In [29]:
lsit_of_list[3][2]

15

In [30]:
lsit_of_list[3][1:3]

[10, 15]

In [31]:
lsit_of_list[3][::2]

[5, 15]

In [32]:
lsit_of_list[3][-2]

15

In [33]:
lsit_of_list[3][-4:-1]

[5, 10, 15]

In [36]:
lsit_of_list[-1]

[5, 10, 15, 20]

In [34]:
ls=[1,2,3,4,5]
ls[:-1]

[1, 2, 3, 4]

In [35]:
ls[-4:-1]

[2, 3, 4]

In [37]:
lisst=[]
lisst.append(10)

In [38]:
lisst

[10]

In [39]:
lisst.append("string")

In [40]:
lisst.append("This string will at the last of the list..")

In [41]:
lisst.append(40.2)

In [42]:
lisst

[10, 'string', 'This string will at the last of the list..', 40.2]

In [43]:
list1=[50]

In [44]:
list1.insert(0,"This will be placed at the zeroth position and the element at the zero th position will shift towards first index ")

In [45]:
list1

['This will be placed at the zeroth position and the element at the zero th position will shift towards first index ',
 50]

In [46]:
list1.insert(2,4444.000)

In [47]:
list1.insert(10,2)

In [48]:
list1

['This will be placed at the zeroth position and the element at the zero th position will shift towards first index ',
 50,
 4444.0,
 2]

In [49]:
list1.insert(5,60)

In [50]:
list1

['This will be placed at the zeroth position and the element at the zero th position will shift towards first index ',
 50,
 4444.0,
 2,
 60]

In [51]:
list1+["concatination"]

['This will be placed at the zeroth position and the element at the zero th position will shift towards first index ',
 50,
 4444.0,
 2,
 60,
 'concatination']

In [53]:
list2=[range(10)]
list2

[range(0, 10)]

In [54]:
list2=list(range(10))

In [55]:
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
int(list)<3

TypeError: int() argument must be a string, a bytes-like object or a number, not 'type'

In [59]:
list3=list(range(2,50))

In [60]:
list3

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [61]:
list4=list(range(20,50,5))

In [62]:
list4

[20, 25, 30, 35, 40, 45]

In [63]:
list4=list(range(20,51,5))

In [64]:
list4

[20, 25, 30, 35, 40, 45, 50]

In [65]:
max(list4)

50

In [66]:
min(list4)

20

In [74]:
#if we want to call an element at the index below passed as a parameter in the index method.
list4.index(20)

0

In [75]:
list4.index(50)

6

In [76]:
list4.index(45)

5

In [78]:
list4.index(40)

4

In [79]:
list4.index(35)

3

In [80]:
list4.index(30)

2

In [81]:
list4.index(25)

1

In [83]:
list4.index(20)

0

In [84]:
#This counts how many times the number comes in the list
list4.count(20)

1

In [85]:
list4.count(30)

1

In [86]:
list5=[1,11,1,1,1]
list5.count(1)

4

In [87]:
list5.count(11)

1

In [88]:
import numpy as np

In [89]:
array1=np.array([10,11.1,'string'])

In [90]:
array1

array(['10', '11.1', 'string'], dtype='<U32')

In [95]:
array1=np.array([[10,20,30],[10.6,30.4,500.2]])
array1

array([[ 10. ,  20. ,  30. ],
       [ 10.6,  30.4, 500.2]])

In [96]:
array=np.array(['Umair Khan',10,20.3,True])
array

array(['Umair Khan', '10', '20.3', 'True'], dtype='<U10')

In [97]:
array3=np.array([20.3,5,True])

In [98]:
array3

array([20.3,  5. ,  1. ])

In [99]:
array4=np.array([20,50,False])
array4

array([20, 50,  0])

In [101]:
array5=np.array([[20,30,50],[44,55,66]])
array5

array([[20, 30, 50],
       [44, 55, 66]])

In [102]:
array5[0]

array([20, 30, 50])

In [104]:
array5[0][0]

20

In [105]:
array5[0][:-1]

array([20, 30])

In [106]:
array5[1][0:-1:2]

array([44])

In [108]:
#The array behaves same as matrix since we can add, subtract, multiply and divide matrix, the same things we can do with array.
array5*5

array([[100, 150, 250],
       [220, 275, 330]])

In [109]:
array5-100

array([[-80, -70, -50],
       [-56, -45, -34]])

In [110]:
#This will generate a random integer among 10
random=np.random.randint(10)

In [111]:
random

8

In [116]:
random1=np.random.randint(1,10)

In [117]:
random1

6

In [118]:
random2=np.random.randint(1,20,5)

In [119]:
random2

array([ 5,  4,  2, 19, 18])

In [120]:
random2>2

array([ True,  True, False,  True,  True])

In [123]:
random2[random2>2]

array([ 5,  4, 19, 18])

In [124]:
elements=np.array([range(100)])
elements

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [133]:
elements[elements%5==0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
#THANK YOU